#!/usr/bin/env bash

# Usage: 'install perlversion port'
#	e.g. build-docker-image 5.30.2
#	build-docker-image 5.18.2 --thread

# You'll need to 'apt install socat'

# FIXME: remove temporary files on error or signal, and/or use stdin

# TODO: check if the given port is free
# TODO: Support distributions other than only Debian

# docker run -it --entrypoint /bin/bash smoker-perl-5.33.1 -s

set -e

typeset -r PERL=${1:-5.32.0}
typeset -r TMPDIR=${TMPDIR:-/tmp}
# Doesn't work on ARM
# typeset -r NPROC=$(grep ^cpu\\scores /proc/cpuinfo | uniq | awk '{print $4}')
typeset -r NPROC=$(grep -c ^processor /proc/cpuinfo)

shift
# Use $* instead of $@ as the array is being assigned to a string
typeset -r ARGS="$*"
typeset -r HOSTNAME=$(echo "smoker-${PERL}$ARGS" | sed s/\\./-/g | sed s/--/-/g | sed 's/ //g').$(hostname)

if [[ $ARGS != "" ]]; then
	typeset -r NAME=perl-"$PERL"$(echo "$ARGS" | sed s/--/-/g | sed 's/ //g')
	typeset -r BUILDCMD="source ~/perl5/perlbrew/etc/bashrc && perlbrew install -j$NPROC -n perl-$PERL -Accflags='-O2 -pipe -Wall -Wextra -mtune=native -march=native' -Dusedevel $ARGS --as $NAME"
else
	typeset -r NAME="perl-$PERL"
	typeset -r BUILDCMD="source ~/perl5/perlbrew/etc/bashrc && perlbrew install -j$NPROC -n $NAME -Accflags='-O2 -pipe -Wall -Wextra -mtune=native -march=native' -Dusedevel"
fi

# rm -f config.ini smoker.config.sample nhorne.json
# ln "$HOME/.cpanreporter/config.ini" .
rm -f smoker.config.sample nhorne.json
echo 'clean_after_test=1' > smoker.config.sample
cp "$HOME/.metabase/nhorne.json" .
# rm -f MyConfig.pm
# ln "$HOME/.cpan/CPAN/MyConfig.pm" .

cat > setup.$$ <<EOF
#!/usr/bin/env bash

# Install system programs needed by the smoker

set -ex

# hostname $HOSTNAME.bandsman.co.uk
# export http_proxy="http://zack:3128"
# export https_proxy="http://zack:3128"
# mount -o remount,rw,hidepid=2 /proc
# yum update && yum install git curl bzip2 bison byacc patch gcc make autoconf sqlite3
export DEBIAN_FRONTEND=noninteractive
apt-get update && apt-get -y upgrade && apt-get --no-install-recommends install -y libpam-tmpdir git procps curl bzip2 bison byacc patch netbase gcc make ca-certificates autoconf libxml2-dev sqlite3 libterm-readline-perl-perl && apt-get autoremove && apt-get autoclean && apt-get clean && rm -rf /var/lib/apt/lists/*
echo $HOSTNAME > /etc/hostname
EOF

cat > build.$$ <<EOF
#!/usr/bin/env bash

set -ex

# Install user programs needed by the smoker

curl -L https://install.perlbrew.pl | bash

export CFLAGS="-O2 -pipe -Wall -Wextra -mtune=native -march=native"
source ~/perl5/perlbrew/etc/bashrc && $BUILDCMD
rm -rf perl5/perlbrew/dists perl5/perlbrew/build perl5/perlbrew/*log smoker/dockerprojects

# perlbrew use $NAME && perl -MCPAN -e 'CPAN::Shell->install("ExtUtils::MakeMaker", "Test::Reporter::Transport::Metabase", "CPAN::Reporter", "Data::Dumper")'
perlbrew use $NAME && cpan -iT ExtUtils::MakeMaker CPAN::Reporter Data::Dumper Test::Reporter::Transport::Metabase
git clone https://github.com/nigelhorne/smoker.git && cd smoker/bin && ./loadall2 && ./loadall3 && ./loadall5
cpan -fiT IPC::System::Simple
cd && git clone https://github.com/nigelhorne/li.git && cd li && cc li.c && ./a.out -r0l ../perl5

# TODO
# cpancleanup
# yum uninstall git bison byacc
# yum clean all
cd && rm -rf .cpan/sources/authors/id/? .cpan/build /tmp/* li smoker/dockerprojects smoker/bin/loadall? smoker/.git
# apt-get purge -y git bison byacc

EOF

cat > "$TMPDIR/dockerfile" <<EOF
FROM debian
LABEL Maintainer="njh@bandsman.co.uk"
LABEL Description="CPAN Smoker image"
COPY setup.$$ /tmp/setup
RUN bash /tmp/setup && rm /tmp/setup

RUN useradd -ms /bin/bash smoker
RUN apt-get -y --allow-remove-essential purge adduser e2fsprogs e2fslibs
USER smoker
WORKDIR /home/smoker

ENV TEST_JOBS $NPROC
ENV HARNESS_OPTIONS c:j$NPROC
ENV PERL_MM_USE_DEFAULT 1
ENV AUTOMATED_TESTING 1

RUN mkdir -p .cpanreporter .cpan/CPAN .metabase
COPY --chown=smoker config.ini .cpanreporter/config.ini
COPY --chown=smoker nhorne.json .metabase/nhorne.json
COPY --chown=smoker smoker.config.sample .smokerrc
COPY --chown=smoker MyConfig.pm .cpan/CPAN/MyConfig.pm
COPY --chown=smoker build.$$ build
# Stop CPAN modules trying to put stuff in the home directory
RUN bash build && rm build && chmod 500 /home/smoker && chmod 400 /home/smoker/.metabase/nhorne.json

ENV PATH \$PATH::
# CMD ["/bin/bash"]
CMD ["/bin/bash", "-c", "source perl5/perlbrew/etc/bashrc && perlbrew use $NAME && cd smoker/bin && PATH=\$PATH:: ./smoker"]
EOF
docker build -t smoker-$NAME -f "$TMPDIR/dockerfile" .

rm -f "$TMPDIR/dockerfile" setup.$$ build.$$

# Run a smoker every 6 hours, ensure the previous one dies in case it is hung
echo "add '18 * * * * /usr/bin/docker container prune -f>/dev/null' to crontab if not already there"
echo "add '19 0,6,12,18 * * * /usr/bin/timeout 5h /usr/bin/docker run --hostname=$HOSTNAME.bandsman.co.uk --log-driver syslog --log-opt syslog-address=udp://loghost:42185 --log-opt tag=$HOSTNAME --log-opt syslog-format=rfc3164 -dt --name smoker-$NAME smoker-$NAME > /dev/null' to crontab"
