#!/usr/bin/env bash

set -xe

# Prevent modules being tested from reaching out to the Internet
/sbin/iptables -F DOCKER-USER
/sbin/iptables -A DOCKER-USER -s 192.168.0.0/16 -j ACCEPT
/sbin/iptables -A DOCKER-USER -d 192.168.0.0/16 -j ACCEPT
/sbin/iptables -A DOCKER-USER -d 127.0.0.0/24 -j ACCEPT
/sbin/iptables -A DOCKER-USER -s 127.0.0.0/24 -j ACCEPT
# Allow connections to the loghost machine
/sbin/iptables -A DOCKER-USER -d 51.15.142.52 -j ACCEPT
/sbin/iptables -A DOCKER-USER -j LOG --log-prefix "Blocked traffic: " --log-level 7
/sbin/iptables -A DOCKER-USER -j RETURN
