#!/usr/bin/env bash

# docker exec -it a4e33ebd3bde /bin/bash

# Are the images smoking?
for i in `docker ps | tail +2 | awk '{ print $1; }'`
do
	echo $i:
	docker exec -it $i /bin/ls -l .cpanreporter/reports-sent.db /tmp/smokerdaemon.err
done
