---

# To run on all machines:
#	ansible-playbook -vv -i playbook.yml -k
# To run on debian machines:
#	ansible-playbook -vv -i playbook.yml -l debian -k

- hosts: smokers
  remote_user: njh
  become: true

  roles:
    - role: smoker
      tags: smoker

  pre_tasks:
    - name: get package facts
      package_facts:
        manager: auto
      tags:
        always

    - name: get service facts
      service_facts:
      tags:
        always
